name: Validation to merge master branch, Deploy GitHub pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run lint
        npm run build --if-present
        npm test
        npm run e2e
      env:
        CI: true
    - name: deploy
      run: npm run deploy:gh-pages
